
####################################################################################
# Generated by Vivado 2019.1 built on 'Fri May 24 14:47:09 MDT 2019' by 'xbuild'
# Command Used: write_xdc ./Sources/xdc/fplan.xdc -force
####################################################################################


# User Generated miscellaneous constraints 

set_property HD.RECONFIGURABLE true [get_cells system_i/ml_regressor_0/U0/ml_regressor_v1_0_S00_AXI_inst/my_regressor]

# User Generated physical constraints 

create_pblock pblock_rp_instance
add_cells_to_pblock [get_pblocks pblock_rp_instance] [get_cells -quiet [list system_i/ml_regressor_0/U0/ml_regressor_v1_0_S00_AXI_inst/my_regressor]]
resize_pblock [get_pblocks pblock_rp_instance] -add {SLICE_X52Y1:SLICE_X111Y48}
resize_pblock [get_pblocks pblock_rp_instance] -add {DSP48_X3Y2:DSP48_X4Y17}

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
